### ISSUE TITLE
Repeated "the"

### ISSUE THREAD

**Issue by vansky** [languageMIT/naturalstories#2]
Based on the duplicated subject IDs but varying RTs for word 228 of story 3 in processed_RTs.tsv, it looks like subjects saw "she carried in the the old apron" in story three, with "the" (word 228) repeated. Is that correct? 

If so, I think all_stories.tok should be updated to reflect this.

**Comment by Futrell** [comment]
We figured out that participants got shown a blank token around that part of story 3. I think the extra RT you are finding is for the blank token. I'm looking into it to see if that is the case. If it turns out it's for the blank token, we will have to decide what to do with the RT.

**Comment by Futrell** [comment]
I can confirm this was the problem. We realigned the RTs to correct for the blank token, but we didn't remove the RT for the blank token itself. That has been done now.

**Comment by vansky** [comment]
Ok, great. Thanks.
